// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    ElAlert: typeof import('element-plus/lib')['ElAlert']
    ElButton: typeof import('element-plus/lib')['ElButton']
    ElCard: typeof import('element-plus/lib')['ElCard']
    ElContainer: typeof import('element-plus/lib')['ElContainer']
    ElDescriptions: typeof import('element-plus/lib')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/lib')['ElDescriptionsItem']
    ElDivider: typeof import('element-plus/lib')['ElDivider']
    ElFooter: typeof import('element-plus/lib')['ElFooter']
    ElForm: typeof import('element-plus/lib')['ElForm']
    ElFormItem: typeof import('element-plus/lib')['ElFormItem']
    ElHeader: typeof import('element-plus/lib')['ElHeader']
    ElInput: typeof import('element-plus/lib')['ElInput']
    ElMain: typeof import('element-plus/lib')['ElMain']
    ElMenu: typeof import('element-plus/lib')['ElMenu']
    ElMenuItem: typeof import('element-plus/lib')['ElMenuItem']
    ElOption: typeof import('element-plus/lib')['ElOption']
    ElPageHeader: typeof import('element-plus/lib')['ElPageHeader']
    ElSelect: typeof import('element-plus/lib')['ElSelect']
    ElSubMenu: typeof import('element-plus/lib')['ElSubMenu']
    ElTable: typeof import('element-plus/lib')['ElTable']
    ElTableColumn: typeof import('element-plus/lib')['ElTableColumn']
    ElTag: typeof import('element-plus/lib')['ElTag']
    Footer: typeof import('./components/Footer.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
